services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: baknusitcare-db
    restart: always
    user: root
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=BaknusSuperPassword123!
      - MSSQL_SA_PASSWORD=BaknusSuperPassword123!
      - MSSQL_PID=Developer
    ports:
      - "14333:1433"
    volumes:
      - mssql_data_itcare:/var/opt/mssql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: baknusitcare-web
    restart: always
    ports:
      - "8089:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - UseSqlite=false
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=BaknusITCareDb;User Id=sa;Password=BaknusSuperPassword123!;TrustServerCertificate=True;Encrypt=False;
      - Mailcow__ApiUrl=https://mail.smk.baktinusantara666.sch.id
      - Mailcow__ApiKey=925B68-0FF6BB-36B760-F6C051-AAF343
      - Mailcow__SmtpHost=mail.smk.baktinusantara666.sch.id
      - Mailcow__SmtpPort=587
      - Mailcow__SmtpUsername=admin@smk.baktinusantara666.sch.id
      - Mailcow__SmtpPassword=buhun666
      - Mailcow__SenderName=BaknusITCare - Layanan IT Sekolah
    depends_on:
      - db

volumes:
  mssql_data_itcare:
    driver: local
